favicon: /images/favicon.ico
## banner: /images/abot.png

logo:
  expanded: /images/logo@2x.png
  collapsed: /images/logo-collapsed@2x.png
  dark: /images/logo@2x.png

flag:
  - name: Chinese
    default: true
    icon: flag-cn
    index: /index.html

search: true

userDefinedSearchData:
  custom: false
  thisSearch: https://www.baidu.com/s?wd=
  thisSearchIcon: url(https://www.baidu.com/favicon.ico)
  hotStatus: true
  data:
    - name: ç™¾åº¦
      img: url(https://www.baidu.com/favicon.ico)
      url: https://www.baidu.com/s?wd=


expandAll: false
menu:
  - name: çƒ­é—¨æ¨è
    icon: fa-brands fa-hotjar
    config: hottj
  - name: è‹±æ–‡æ•™å­¦
    icon: fa-solid fa-school
    submenu:
      - name: è‹±æ–‡æ•™å­¦
        icon: fa-solid fa-graduation-cap
        config: enjx
      - name: è‹±æ–‡å¬åŠ›
        icon: fa fa-assistive-listening-systems
        config: entl
      - name: è‹±æ–‡å·¥å…·
        icon: fa-solid fa-screwdriver-wrench
        config: engj
  - name: ä¸ªäººå­¦ä¹ 
    icon: fa-solid fa-book-open
    config: grxx
  - name: äººå·¥æ™ºèƒ½
    icon: fa-solid fa-robot
    config: openai
  - name: å¸¸ç”¨å·¥å…·
    icon: fa-solid fa-toolbox
    config: hotTools
  - name: å‹æƒ…é“¾æ¥
    icon: fa-solid fa-user-plus
    config: myBlog
  # - name: å…¶ä»–å·¥å…·
    # icon: fas fa-tools
    # submenu:
      # - name: å¼€å‘å·¥å…·
        # icon: fas fa-tools
        # config: devTools
      # - name: æµ‹è¯•
        # icon: fas fa-tools
        # config: devTools
    
## å‹æƒ…é“¾æ¥
myBlog:
  - name: æœ¨å­å°
    url: https://muziyin.top/
    img: /images/logos/myblog.png
    description: 'è‹±æ–‡èµ„æºåšå®¢'
  - name: Free-Chat
    url: https://ai.mkids.top/
    img: /images/logos/chatweb.jpg
    description: 'å…è´¹chatgptï¼Œä½¿ç”¨çš„æ˜¯Access Tokenï¼Œæœ‰é™åˆ¶ï¼Œå¦‚ä¸èƒ½ä½¿ç”¨å¯ä»¥æ¢ä¸ªæ—¶é—´'
  - name: Chat! v2.0
    url: https://chat.mkids.top/
    img: /images/logos/chatweb.jpg
    description: 'ä¸ªäººæ­å»ºï¼Œå¯ä½¿ç”¨ä¸­è½¬keyï¼Œä¹Ÿå¯ä»¥ä½¿ç”¨å®˜æ–¹key'
  - name: è´­ä¹°ä¸­è½¬Key
    url: https://afdian.net/a/davidgy
    img: https://pic1.afdiancdn.com/user/a877bc7e4ee911edaa0252540025c377/avatar/8323030b5f7c4d6e3b8e8927c1beff84_w2048_h2048_s5895.png?imageView2/1/w/120/h/120
    description: 'æ­é…Chat! v2.0ä½¿ç”¨ï¼Œä¾¿å®œ'
    
## å¼€å‘å·¥å…·
# devTools:
  # - name: Github
    # url: https://github.com/
    # img: /images/logos/github.png
    # description: é¢å‘å¼€æºåŠç§æœ‰è½¯ä»¶é¡¹ç›®çš„æ‰˜ç®¡å¹³å°ã€‚


about:
  url: /about/
  icon: far fa-heart
  name: å…¬å‘Š

aboutPage:
  website:
    head: å…¬å‘Šæ 
    html: '<p>ä¸è¦è¯•å›¾è”ç³»æˆ‘ï¼šæœ‰äº›ç½‘ç«™æ‰“ä¸å¼€ï¼Œå¯èƒ½ä½ éœ€è¦é­”æ³•ï¼çœ‹ä¸‹é¢ğŸ‘‡</p>
  <p><a href="https://hxlm.io/#/register?code=72Pgcx1k">(èƒ½å¼€ChatGPT)</a> || <a href="https://jsqpro.vip/auth/register?code=7Ynd4ZfdfyGt">(è€ç‰Œäº†ï¼Œå¥½ç”¨)</a> || <a href="https://invite.efshop.cc#/register?code=UoHtGFmy">(æ€§ä»·æ¯”å¾ˆé«˜)</a></p>
	<p><a href="https://portal.passgfw.top/#/register?code=mZIxTi3D">(ä¾¿å®œï¼Œè§£é”å¥ˆé)</a> || <a href="https://xn--4gq62f52gdss.com/#/register?code=orLxozVh">(çœŸå¿ƒä¾¿å®œï¼Œç•™å¤‡ç”¨)</a></p>
    <hr>
    <p><a href="https://ihezu.work/mrvryP">å¥ˆé£å°é“º</a>ï¼ˆå¥ˆé£ã€è¿ªå£«å°¼+ã€æ²¹ç®¡ã€Spotify ç­‰å½±éŸ³è´¦å·åˆç§Ÿï¼‰</p>
	<p><a href="https://nf.video/4AkXI">é“¶æ²³å½•åƒå±€</a>ï¼ˆNetflixã€Apple Oneã€Disneyã€Youtubeã€HBOã€Spotify ç­‰å½±éŸ³è´¦å·åˆç§Ÿï¼Œç°åœ¨è¿˜æœ‰chatgptã€midjourneyç­‰ç­‰ï¼‰</p>
    <hr>
	<p><a href="https://afdian.net/a/davidgy">ChatGPTä¸­è½¬keyè´­ä¹°</a>ï¼ˆä¸­è½¬çš„å¥½å¤„åœ¨äºä¸ç”¨é­”æ³•ï¼Œä¾¿å®œï¼Œåªç”¨å¡«å†™æ¥å£å’ŒKEYå°±èƒ½ä½¿ç”¨ï¼Œæ–¹ä¾¿ï¼‰</p>'
  # webmaster:
    # head: å…¬å‘Šæ 
    # name: HCLonely
    # url: https://blog.hclonely.com/
    # img: /images/logos/myblog.png
    # description: æ‡’äººä¸€ä¸ª
    # html: '<br /><blockquote><p>æœ¬ç«™æ˜¯<a href="https://github.com/HCLonely">HCLonely</a>åŸºäº<a href="https://github.com/WebStackPage/WebStackPage.github.io">WebStackPage</a>é¡¹ç›®åšçš„ä¸€æ¬¾<a href="https://hexo.io/">Hexo</a>ä¸»é¢˜ã€‚</p></blockquote>'

since: 2018

busuanzi:
  enable: true
  position: sidebar # 'footer','sidebar'
  pv: æœ¬ç«™æ€»è®¿é—®é‡$pv
  uv: æœ¬ç«™æ€»è®¿å®¢æ•°$uv

custom:
  head: |- # ä»¥ä¸‹å†…å®¹æ’å…¥åˆ°<head></head>æ ‡ç­¾å†…ï¼Œå¯è®¾ç½®å¤šè¡Œï¼Œæ³¨æ„æ¯è¡Œå¼€å¤´è‡³å°‘å››ä¸ªç©ºæ ¼
    <!-- ç›´æ¥æ·»åŠ htmlå†…å®¹å³å¯ -->   
    <!-- å¯è®¾ç½®å¤šè¡Œ -->
  body: |- # ä»¥ä¸‹å†…å®¹æ’å…¥åˆ°</body>æ ‡ç­¾ä¹‹å‰ï¼Œå¯è®¾ç½®å¤šè¡Œï¼Œæ³¨æ„æ¯è¡Œå¼€å¤´è‡³å°‘å››ä¸ªç©ºæ ¼
    <!-- ç›´æ¥æ·»åŠ htmlå†…å®¹å³å¯ -->
    <!-- å¯è®¾ç½®å¤šè¡Œ -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
